version: '3'

services:
  webapp:
    container_name: webapp
    build:
      dockerfile: ./apps/webapp/Dockerfile
      context: .
    ports:
      - "8081:8081"
    env_file:
      - ./apps/webapp/.env
 