name: Docker CI

on:
  push:
    branches: [ master ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Build & push Docker image
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: ${{ github.event.repository.name }}
          tags: latest
          target: website
          registry: ghcr.io
          dockerfile: ./Dockerfile
          username: ${{ github.actor }}
          password: ${{ secrets.GH_PAT }}